version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html/
hooks:
  BeforeInstall:
    - location: chmod +x scripts/install_dependencies.sh
      timeout: 120
      runas: root
  AfterInstall:
    - location: chmod +x scripts/start_server.sh
      timeout: 120
      runas: root
