version: 0.2
phases:
  install:
    commands:
      - echo Currently installing nginx
  
  build:
    commands:
      - echo Building started
      - cp index.html .

  post_build:
    commands:
      - echo configuring nginx

artifacts:
  files:
    - index.html
