version: 0.2
phases:
  install:
    commands:
      - echo Currently installing nginx
      - sudo yum install nginx -y
  
  build:
    commands:
      - echo Building started
      - cp index.html /usr/share/nginx/html/

  post_build:
    commands:
      - echo configuring nginx

artifacts:
  files:
    - /usr/share/nginx/html/index.html
