version: 0.2
phases:
  install:
    commands:
      - echo making a new folder in usr
      - mkdir /usr/build
  
  build:
    commands:
      - echo Building started on `date`
      - cp -r * /usr/build

  post_build:
    commands:
      - echo configuring nginx

artifacts:
  files:
    - /usr/build/*
